### ISSUE TITLE
Please, add the "gradle" directory

### ISSUE THREAD

**Issue by TheBlusky** [xroche/httrack-android#1]
Hello !
The `./gradlew` script does not work:
`Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain`

Adding the `gradle` directory (containing `gradle` jar) to the repository should solve the issue.

**Comment by xroche** [comment]
I did not include the file in the GIT source actually. This is now done (310b81a031a7862c49c6b4c812fa2f588559b234)
